### ISSUE TITLE
Explore using official yelp API to get wifi status of business rather than scraping

### ISSUE THREAD

**Issue by jwon** [romebop/hack-smc-team7#1]
wifi is not an official field in the Yelp Business API (https://www.yelp.com/developers/documentation/v2/business) but we should still explore it to see if we can somehow get it officially.

**Comment by jwon** [comment]
@romebop can you take a look at this please? :)

**Comment by njazari** [comment]
I looked at the Google Places API and Foursquare API and neither of them provide WIFI data either. This app (http://readwrite.com/2011/11/23/4sqwifi_app_helps_foursquare_users_find_free_wifi) essentially does what we tried with the Fousquare API. 
I'm not sure it we can officially get that information without Yelp adding it themselves.

**Comment by romebop** [comment]
it turns out we can just query "wifi" and get all the information we need.

probably no need to do a separate http request and parse the html even

On Tue, Aug 18, 2015 at 11:24 AM, njazari notifications@github.com wrote:

> I looked at the Google Places API and Foursquare API and neither of them
> provide WIFI data either. This app (
> http://readwrite.com/2011/11/23/4sqwifi_app_helps_foursquare_users_find_free_wifi)
> essentially does what we tried with the Fousquare API.
> I'm not sure it we can officially get that information without Yelp adding
> it themselves.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/romebop/hack-smc-team7/issues/1#issuecomment-132307762
> .

## 

Saerom Park

**Comment by jwon** [comment]
@romebop Can you post the HTTP URL on the Yelp API that we need to hit to get the data please?

**Comment by njazari** [comment]
Cant believe we didn't think of that. They do all the work for us...

**Comment by romebop** [comment]
yeah, our app is now trivial, but it's fine. it was a good learning
experience. i'll fix it up and do a pull request

On Tue, Aug 18, 2015 at 11:34 AM, njazari notifications@github.com wrote:

> Cant believe we didn't think of that. They do all the work for us...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/romebop/hack-smc-team7/issues/1#issuecomment-132311594
> .

## 

Saerom Park

**Comment by njazari** [comment]
Yeah just change all my unnecessary queries to say wifi. Yelp will limit us to 20 results. Is that enough?

**Comment by njazari** [comment]
@jwon All he had to do was use "wifi" as the search term, and Yelp will filter all restaurants by wifi for us. So all the parsing was unnecessary.

**Comment by jwon** [comment]
Closed by https://github.com/romebop/hack-smc-team7/pull/2
